name = "ReassemblyModifier"
uuid = "5c6fc2ef-bd28-461b-aab5-8d5bbc7b7e55"
authors = ["Magnus Ramsey"]
version = "1.0.0-DEV"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
